### ISSUE TITLE
BrokenPipeError during training process

### ISSUE THREAD

**Issue by fyaft2012** [pxiangwu/MotionNet#9]
Hi Wu,

Thanks for your excellent work! When I train the network with provided training script, it always shows errors at some batches or epochs. error information is as:
#########################################
Traceback (most recent call last):
  File "train_multi_seq.py", line 611, in <module>
    main()
  File "train_multi_seq.py", line 184, in main
    = train(model, criterion, trainloader, optimizer, device, epoch)
  File "train_multi_seq.py", line 212, in train
    for i, data in enumerate(trainloader, 0):
  File "/home/aiserver/anaconda3/envs/MotionNet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/aiserver/anaconda3/envs/MotionNet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
BrokenPipeError: Traceback (most recent call last):
  File "/home/aiserver/anaconda3/envs/MotionNet/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/aiserver/anaconda3/envs/MotionNet/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/aiserver/FangYang/MotionNet/data/nuscenes_dataloader.py", line 58, in __getitem__
    if idx in self.cache:
  File "<string>", line 2, in __contains__
  File "/home/aiserver/anaconda3/envs/MotionNet/lib/python3.7/multiprocessing/managers.py", line 818, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/home/aiserver/anaconda3/envs/MotionNet/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/aiserver/anaconda3/envs/MotionNet/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/aiserver/anaconda3/envs/MotionNet/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

#############################################
I have no idea why it happened, could you help me figure it out ? Thank you!

**Comment by pxiangwu** [comment]
Hi, I never encountered this issue before. Which version of Pytorch are you using? 

I tested my code on Pytorch1.0 and 1.1. Not sure if the latest Pytorch version (e.g., 1.6) would work well.

**Comment by fyaft2012** [comment]
Hi, I use the pytorch 1.1.0, not the latest one. And it runs on Ubuntu 18.04 (I previously trained on 16.04, same problem happened), with RTX 2080, 32GB RAM.

**Comment by pxiangwu** [comment]
@fyaft2012 , could you debug the code by setting the num_worker = 0? This would be helpful to check what happens.

**Comment by fyaft2012** [comment]
Hi Wu, okay I am just debugging as what you suggest. Let's see what will happen, while the speed is much reduced after setting num_worker = 0. I will let you know whether it helps or not. Thanks!

**Comment by pxiangwu** [comment]
Sure. Let me know what happens since I am quite curious about this. From the error you showed above, it could possibly related to the multithread data loading.

Also, from the error reported, one potential work-around could be: set the size of `self.cache` to be 0. In this way, we will not cache the pre-loaded data in the memory (although the speed could be slowed down a little bit).

**Comment by fyaft2012** [comment]
Okay, I will try both of them. And let you know the results.

**Comment by pxiangwu** [comment]
Also, one thing I forgot to mention. You may also need to observe the CPU memory to see if it is used up by the `cache`. Not sure 32GB RAM is OK, since I run the code on the cluster with 1TB memory ... 

If the memory is not enough, you may reduce the cache size.

**Comment by fyaft2012** [comment]
Okay, I see. Thank you!
